/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sS_Interface;

import java.util.ArrayList;
import sS_Codigo.Produto;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author João Gabriel
 */
public class FormCadProduto extends javax.swing.JFrame {

    public static DefaultTableModel modeloSushi;
    public String[] acrescimo = new String[4];
    public static ArrayList<Produto> listaProdutos = new ArrayList<>();

    /**
     * Creates new form FormCadProduto
     */
    public FormCadProduto() {

        initComponents();

        modeloSushi = (DefaultTableModel) tabelaSushi.getModel();
        atualizarTabela();
        desabilitarEdicao();
        desabilitarBotoes();

        configurarSelecaoTabela();
    }

    public void habilitarEdicao() {
        jComboBTipo.setEnabled(true);
        jComboBPeixe.setEnabled(true);
        jCheckBCebolinha.setEnabled(true);
        jCheckBCreamCheese.setEnabled(true);
        jCheckBGergelim.setEnabled(true);
        jCheckBPepino.setEnabled(true);
        jTxtPreco.setEnabled(true);
        jTxtQuantidade.setEnabled(true);

    }

    public void desabilitarEdicao() {
        jComboBTipo.setEnabled(false);
        jComboBPeixe.setEnabled(false);
        jCheckBCebolinha.setEnabled(false);
        jCheckBCreamCheese.setEnabled(false);
        jCheckBGergelim.setEnabled(false);
        jCheckBPepino.setEnabled(false);
        jTxtPreco.setEnabled(false);
        jTxtQuantidade.setEnabled(false);
    }

    public void desabilitarBotoes() {
        jButtonNovo.setEnabled(true);
        jButtonCadastrar.setEnabled(false);
        jButtonAlterar.setEnabled(false);
        jButtonLimpar.setEnabled(false);
    }

    public void habilitarBotoes() {
        jButtonNovo.setEnabled(false);
        jButtonCadastrar.setEnabled(true);
        jButtonAlterar.setEnabled(true);
        jButtonLimpar.setEnabled(true);
    }

    public void limpar() {
        jTxtPreco.setText("");
        jTxtQuantidade.setText("");
        jComboBTipo.setSelectedIndex(0);
        jComboBPeixe.setSelectedIndex(0);
        jCheckBCebolinha.setSelected(false);
        jCheckBCreamCheese.setSelected(false);
        jCheckBGergelim.setSelected(false);
        jCheckBPepino.setSelected(false);
    }

    private void configurarSelecaoTabela() {
        jButtonVoltar.setEnabled(true);
        tabelaSushi.getSelectionModel().addListSelectionListener((e) -> {

            if (tabelaSushi.getSelectedRow() == -1) {
                return;
            }

            int l = tabelaSushi.getSelectedRow();

            // Preencher campos automaticamente:
            jComboBPeixe.setSelectedItem(modeloSushi.getValueAt(l, 1).toString());
            jComboBTipo.setSelectedItem(modeloSushi.getValueAt(l, 2).toString());
            jTxtQuantidade.setText(modeloSushi.getValueAt(l, 4).toString());
            jTxtPreco.setText(modeloSushi.getValueAt(l, 5).toString());

            // Recheios
            String recheios = modeloSushi.getValueAt(l, 3).toString();

            jCheckBCebolinha.setSelected(recheios.contains("Cebolinha"));
            jCheckBCreamCheese.setSelected(recheios.contains("Cream Cheese"));
            jCheckBGergelim.setSelected(recheios.contains("Gergelim"));
            jCheckBPepino.setSelected(recheios.contains("Pepino"));

            habilitarEdicao();
            jButtonAlterar.setEnabled(true);
        });
    }

    public boolean verificacaoFormCompleto() {
        boolean formularioCompleto = false;
        if (jTxtPreco.getText() != "" && jTxtQuantidade.getText() != "" && jComboBPeixe.getSelectedIndex() != 0 && jComboBTipo.getSelectedIndex() != 0) {
            formularioCompleto = true;
        }
        return formularioCompleto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBTipo = new javax.swing.JComboBox<>();
        jComboBPeixe = new javax.swing.JComboBox<>();
        jButtonNovo = new javax.swing.JButton();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTxtPreco = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTxtQuantidade = new javax.swing.JTextField();
        jCheckBCreamCheese = new javax.swing.JCheckBox();
        jCheckBPepino = new javax.swing.JCheckBox();
        jCheckBCebolinha = new javax.swing.JCheckBox();
        jCheckBGergelim = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaSushi = new javax.swing.JTable();
        jButtonVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 102));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Tipo:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Peixe:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Recheio:");

        jComboBTipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha uma opção", "Hot Holl", "Hossomaki", "Sashimi", "Nigiri", "Temaki", "Outro", " " }));
        jComboBTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBTipoActionPerformed(evt);
            }
        });

        jComboBPeixe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBPeixe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha uma opção", "Salmão", "Atum", "Tilápia", "Kani", "Camarão" }));

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Preço:");

        jTxtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtPrecoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Quantidade:");

        jTxtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtQuantidadeActionPerformed(evt);
            }
        });

        jCheckBCreamCheese.setText("Cream Cheese ");
        jCheckBCreamCheese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBCreamCheeseActionPerformed(evt);
            }
        });

        jCheckBPepino.setText("Pepino");

        jCheckBCebolinha.setText("Cebolinha");

        jCheckBGergelim.setText("Gergelim ");

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel9.setText("(5R$/ Recheio)");

        tabelaSushi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Peixe", "Tipo", "Recheio", "Quantidade", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaSushi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaSushiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaSushi);

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBPeixe, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBCreamCheese)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBPepino))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBCebolinha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBGergelim))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBPeixe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jTxtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jCheckBCreamCheese)
                                        .addComponent(jTxtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jCheckBPepino)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBGergelim)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jCheckBCebolinha)
                                        .addComponent(jLabel9)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(96, 96, 96)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(431, 431, 431))
        );

        jLabel1.setFont(new java.awt.Font("Yu Gothic Light", 1, 36)); // NOI18N
        jLabel1.setText("Cadastrar Sushi");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sushi.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBTipoActionPerformed

    private void jTxtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtQuantidadeActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // TODO add your handling code here:
        habilitarBotoes();
        jButtonVoltar.setEnabled(false);
        habilitarEdicao();
        limpar();

    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void atualizarTabela() {

        DefaultTableModel dtm = (DefaultTableModel) tabelaSushi.getModel();
        dtm.setRowCount(0);

        for (Produto p : Produto.produto) {

            dtm.addRow(new Object[]{
                p.getCodProduto(),
                p.getTipo(),
                String.join(", ", p.getRecheio()),
                p.getPeixe(),
                p.getPrecoCusto(),
                p.getPrecoVenda(),
                p.getQuantDisponivel(),
                p.getQuantVendas()
            });
        }
    }

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        // TODO add your handling code here:
        jButtonVoltar.setEnabled(true);
        if (verificacaoFormCompleto()) {
            //------------------------------------------------------------------------------------------------
            int cod = Produto.gerarCod();
            double preco = Double.parseDouble(jTxtPreco.getText());
            int quantidade = Integer.parseInt(jTxtQuantidade.getText());
            String tipo = jComboBTipo.getSelectedItem().toString();
            String peixe = jComboBPeixe.getSelectedItem().toString();

            // Reinicia o array
            ArrayList<String> recheios = new ArrayList<>();
            double valorAcrescimoTotal = 0;

            // Verifica as caixas
            if (jCheckBCebolinha.isSelected()) {
                recheios.add("Cebolinha");
            }
            if (jCheckBCreamCheese.isSelected()) {
                recheios.add("Cream Cheese");
            }
            if (jCheckBGergelim.isSelected()) {
                recheios.add("Gergelim");
            }
            if (jCheckBPepino.isSelected()) {
                recheios.add("Pepino");
            }

            // Se não selecionou nenhum
            if (recheios.isEmpty()) {
                recheios.add("Sem recheio");
            }

            // Para cada recheio escolhido, custa R$5
            valorAcrescimoTotal = recheios.size() * 5;

            // Transforma a lista em string pronta pra tabela
            String listaRecheios = String.join(", ", recheios);

            //Cria um objeto tipo Conta com as informações!
            Produto produto = new Produto();
            produto.cadastrar(cod, tipo, acrescimo, peixe, preco, quantidade, 0);
            Produto.produto.add(produto);

            //Inicia a tabela
            DefaultTableModel dtm = (DefaultTableModel) tabelaSushi.getModel();

            //Cria linha na tabela
            //Cria a linha da tabela com os seguintes
            modeloSushi.addRow(new Object[]{cod, peixe, tipo, listaRecheios, quantidade, preco});
            // Tabela antes ---> dtm.addRow(new Object[]{cod, peixe, tipo, listaRecheios, quantidade, preco + valorAcrescimoTotal});
            double precoFinal = preco + valorAcrescimoTotal;
            produto.setPrecoVenda(precoFinal);
            jButtonAlterar.setEnabled(true);
            desabilitarEdicao();
            JOptionPane.showMessageDialog(rootPane, "Conta cadastrada com sucesso!");
            desabilitarBotoes();
            jButtonAlterar.setEnabled(true);
            jButtonLimpar.setEnabled(true);

        } else if (!verificacaoFormCompleto()) {
            JOptionPane.showMessageDialog(rootPane, "Preencha todas as informações para continuar!");
            habilitarEdicao();
            jButtonAlterar.setEnabled(false);
        }


    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        // TODO add your handling code here:
        habilitarEdicao();

        int l = tabelaSushi.getSelectedRow();
        if (l == -1) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um item para alterar!");
            return;
        }

        // Lê os valores editados (string dos campos), não sei se tem necessidade mas...
        String peixe = jComboBPeixe.getSelectedItem().toString();
        String tipo = jComboBTipo.getSelectedItem().toString();
        String qtdStr = jTxtQuantidade.getText().trim();
        String precoStr = jTxtPreco.getText().trim();

        // valida campos numéricos
        int qtd;
        double preco;
        // valida quantidade (somente números inteiros)
        if (!qtdStr.matches("\\d+")) {
            JOptionPane.showMessageDialog(rootPane, "Quantidade inválida. Informe um número inteiro.");
            return;
        }
        qtd = Integer.parseInt(qtdStr);

        // valida preço (somente números decimais com ponto OU inteiro)
        if (!precoStr.matches("\\d+(\\.\\d+)?")) {
            JOptionPane.showMessageDialog(rootPane, "Preço inválido. Use ponto como separador decimal.");
            return;
        }
        preco = Double.parseDouble(precoStr);

        // Monta lista de recheios
        ArrayList<String> lista = new ArrayList<>();
        if (jCheckBCebolinha.isSelected()) {
            lista.add("Cebolinha");
        }
        if (jCheckBCreamCheese.isSelected()) {
            lista.add("Cream Cheese");
        }
        if (jCheckBGergelim.isSelected()) {
            lista.add("Gergelim");
        }
        if (jCheckBPepino.isSelected()) {
            lista.add("Pepino");
        }
        if (lista.isEmpty()) {
            lista.add("Sem recheio");
        }
        String recheios = String.join(", ", lista);

        // Atualiza tabela com os TIPOS corretos (Integer e Double)
        modeloSushi.setValueAt(peixe, l, 1);
        modeloSushi.setValueAt(tipo, l, 2);
        modeloSushi.setValueAt(recheios, l, 3);
        modeloSushi.setValueAt(Integer.valueOf(qtd), l, 4);    // Integer
        modeloSushi.setValueAt(Double.valueOf(preco), l, 5);   // Double

        JOptionPane.showMessageDialog(rootPane, "Alterado com sucesso!");


    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jTxtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtPrecoActionPerformed

    private void jCheckBCreamCheeseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBCreamCheeseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBCreamCheeseActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // TODO add your handling code here:
        limpar();

    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        FormIndex formindex = new FormIndex();
        formindex.setVisible(true);
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void tabelaSushiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaSushiMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tabelaSushiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JCheckBox jCheckBCebolinha;
    private javax.swing.JCheckBox jCheckBCreamCheese;
    private javax.swing.JCheckBox jCheckBGergelim;
    private javax.swing.JCheckBox jCheckBPepino;
    private javax.swing.JComboBox<String> jComboBPeixe;
    private javax.swing.JComboBox<String> jComboBTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtPreco;
    private javax.swing.JTextField jTxtQuantidade;
    private javax.swing.JTable tabelaSushi;
    // End of variables declaration//GEN-END:variables
}
